version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"

  react:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
